<a href="https://colab.research.google.com/github/shimohiro/EU_M_Math-Repository/blob/master/Chap05_Ex_13_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#練習問題5-13
import numpy as np
import scipy as sp

B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B

U, s, Vs = sp.linalg.svd(B)
m, n = B.shape

S = sp.linalg.diagsvd(s,m,n)

print('U.S.V* = \n',U@S@Vs)

U.S.V* = 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [2]:
#練習問題5-14
A = np.identity(3)
print(A)
A[0,:] = 1
A[:,0] = 1
A[0,0] = 3
b = np.ones(3)
print(A)
print(b)

(LU,piv) = sp.linalg.lu_factor(A)
L = np.identity(3) + np.tril(LU,-1)
U = np.triu(LU)
P = np.identity(3)[piv]

x = sp.linalg.lu_solve((LU,piv),b)
x

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
[1. 1. 1.]


array([-1.,  2.,  2.])

In [3]:
np.dot(A,sp.linalg.lu_solve((LU,piv),b))

array([1., 1., 1.])