<a href="https://colab.research.google.com/github/shimohiro/EU_M_Math-Repository/blob/master/Chapter_%E2%85%A4_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [5]:
sample_array = np.arange(10)
print('sample_array:',sample_array)

sample_array: [0 1 2 3 4 5 6 7 8 9]


In [6]:
print(sample_array)

sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [7]:
sample_array_slice[0:3] = 10
print(sample_array_slice)

print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [9]:
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [10]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [11]:
sample_names == 'a'

array([ True, False, False, False,  True])

In [12]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [13]:
code_data = np.array([True,True,False,False,True])

x_array = np.array([1,2,3,4,5])

y_array = np.array([100,200,300,400,500])

print(np.where(code_data,x_array,y_array))

[  1   2 300 400   5]


In [14]:
cond_data = np.array([True,True,False,False,True])

print(cond_data)

print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [15]:
sample_data = np.arange(10)
print('元のデータ：', sample_data)
print('すべての要素の平方根：',np.sqrt(sample_data))
print('すべての要素のネイピア指数関数：',np.exp(sample_data))

元のデータ： [0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根： [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
すべての要素のネイピア指数関数： [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [16]:
sample_multi_array_data1 = np.arange(9).reshape(3,3)

print(sample_multi_array_data1)

print('最小値：',sample_multi_array_data1.min())
print('最大値：',sample_multi_array_data1.max())
print('平均：',sample_multi_array_data1.mean())
print('合計：',sample_multi_array_data1.sum())

print('行の合計：',sample_multi_array_data1.sum(axis=1))
print('列の合計：',sample_multi_array_data1.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値： 0
最大値： 8
平均： 4.0
合計： 36
行の合計： [ 3 12 21]
列の合計： [ 9 12 15]


In [17]:
cond_data = np.array([True,True,False,False,True])

print('Trueが少なくとも1つあるかどうか：',cond_data.any())
print('すべてTrueかどうか：',cond_data.all())

Trueが少なくとも1つあるかどうか： True
すべてTrueかどうか： False


In [18]:
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)
print('5より大きい数字がいくつあるか',(sample_multi_array_data1>5).sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字がいくつあるか 3


In [19]:
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('対角成分：',np.diag(sample_multi_array_data1))
print('対角成分の和：',np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分： [0 4 8]
対角成分の和： 12


In [20]:
sample_array = np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
sample_array2 = sample_array.reshape(2,5)
sample_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
print(sample_array3)
print(sample_array4)

np.concatenate([sample_array3,sample_array4],axis=0)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.vstack((sample_array3,sample_array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.concatenate([sample_array3,sample_array4],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [27]:
np.hstack((sample_array3,sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [28]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
sample_array_vstack = np.vstack((sample_array3,sample_array4))

sample_array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
first,second,third=np.split(sample_array_vstack,[1,3])

print(first)

[[1 2 3]]


In [30]:
print(second)

[[4 5 6]
 [7 8 9]]


In [31]:
second[0]

array([4, 5, 6])

In [32]:
print(third)

[[10 11 12]]


In [33]:
sample_array5 = np.array([[13,14,15],[16,17,18],[19,20,21]])
sample_array_vstack2 = np.vstack((sample_array3,sample_array4,sample_array5))

print(sample_array_vstack2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [35]:
first,second,third,fourth=np.split(sample_array_vstack2,[2,3,5])
print('・1つ目：\n',first,'\n')
print('・2つ目：\n',second,'\n')
print('・3つ目：\n',third,'\n')
print('・4つ目：\n',fourth,'\n')

・1つ目：
 [[1 2 3]
 [4 5 6]] 

・2つ目：
 [[7 8 9]] 

・3つ目：
 [[10 11 12]
 [13 14 15]] 

・4つ目：
 [[16 17 18]
 [19 20 21]] 



In [36]:
first[0]

array([1, 2, 3])

In [37]:
first[1]

array([4, 5, 6])

In [38]:
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6])

In [41]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
sample_array + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])